package ru.hardhill.hubservice;




//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------




import org.ksoap2.HeaderProperty;
import org.ksoap2.serialization.*;
import org.ksoap2.transport.*;
import org.kxml2.kdom.Element;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class CFTBasicHttpBinding_IHubService
{
    interface CFTIWcfMethod
    {
        CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope() throws java.lang.Exception;

        java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object result) throws java.lang.Exception;
    }

    String url="http://92.124.194.86:8686/hubservice";

    int timeOut=60000;
    public List< HeaderProperty> httpHeaders;
    public boolean enableLogging;

    CFTIServiceEvents callback;
    public CFTBasicHttpBinding_IHubService(){}

    public CFTBasicHttpBinding_IHubService (CFTIServiceEvents callback)
    {
        this.callback = callback;
    }
    public CFTBasicHttpBinding_IHubService(CFTIServiceEvents callback,String url)
    {
        this.callback = callback;
        this.url = url;
    }

    public CFTBasicHttpBinding_IHubService(CFTIServiceEvents callback,String url,int timeOut)
    {
        this.callback = callback;
        this.url = url;
        this.timeOut=timeOut;
    }

    protected org.ksoap2.transport.Transport createTransport()
    {
        try
        {
            java.net.URI uri = new java.net.URI(url);
            if(uri.getScheme().equalsIgnoreCase("https"))
            {
                int port=uri.getPort()>0?uri.getPort():443;
                return new HttpsTransportSE(uri.getHost(), port, uri.getPath(), timeOut);
            }
            else
            {
                return new HttpTransportSE(url,timeOut);
            }

        }
        catch (java.net.URISyntaxException e)
        {
        }
        return null;
    }
    
    protected CFTExtendedSoapSerializationEnvelope createEnvelope()
    {
        CFTExtendedSoapSerializationEnvelope envelope= new CFTExtendedSoapSerializationEnvelope(CFTExtendedSoapSerializationEnvelope.VER11);
        return envelope;
    }
    
    protected java.util.List sendRequest(String methodName,CFTExtendedSoapSerializationEnvelope envelope,org.ksoap2.transport.Transport transport  )throws java.lang.Exception
    {
        return transport.call(methodName, envelope, httpHeaders);
    }

    java.lang.Object getResult(java.lang.Class destObj,java.lang.Object source,String resultName,CFTExtendedSoapSerializationEnvelope __envelope) throws java.lang.Exception
    {
        if(source==null)
        {
            return null;
        }
        if(source instanceof SoapPrimitive)
        {
            SoapPrimitive soap =(SoapPrimitive)source;
            if(soap.getName().equals(resultName))
            {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
        }
        else
        {
            SoapObject soap = (SoapObject)source;
            if (soap.hasProperty(resultName))
            {
                java.lang.Object j=soap.getProperty(resultName);
                if(j==null)
                {
                    return null;
                }
                java.lang.Object instance=__envelope.get(j,destObj,false);
                return instance;
            }
            else if( soap.getName().equals(resultName)) {
                java.lang.Object instance=__envelope.get(source,destObj,false);
                return instance;
            }
       }

       return null;
    }

        
    public CFTCheckPatientResult CheckPatient(final CFTPatient pat,final Integer idLpu,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTCheckPatientResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","pat",new CFTPatient().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "CheckPatient");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="pat";
                __info.type=CFTPatient.class;
                __info.setValue(pat!=null?pat:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idLpu";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idLpu!=null?idLpu:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTCheckPatientResult)getResult(CFTCheckPatientResult.class,__result,"CheckPatientResult",__envelope);
            }
        },"http://tempuri.org/IHubService/CheckPatient");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTCheckPatientResult>> CheckPatientAsync(final CFTPatient pat,final Integer idLpu,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTCheckPatientResult>() {
            public CFTCheckPatientResult Func() throws java.lang.Exception {
                return CheckPatient( pat,idLpu,guid,idHistory);
            }
        });
    }
    
    public CFTSearchTop10PatientResult SearchTop10Patient(final CFTPatient pat,final Integer idLpu,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTSearchTop10PatientResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","pat",new CFTPatient().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "SearchTop10Patient");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="pat";
                __info.type=CFTPatient.class;
                __info.setValue(pat!=null?pat:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idLpu";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idLpu!=null?idLpu:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTSearchTop10PatientResult)getResult(CFTSearchTop10PatientResult.class,__result,"SearchTop10PatientResult",__envelope);
            }
        },"http://tempuri.org/IHubService/SearchTop10Patient");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTSearchTop10PatientResult>> SearchTop10PatientAsync(final CFTPatient pat,final Integer idLpu,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTSearchTop10PatientResult>() {
            public CFTSearchTop10PatientResult Func() throws java.lang.Exception {
                return SearchTop10Patient( pat,idLpu,guid,idHistory);
            }
        });
    }
    
    public CFTAddNewPatientResult AddNewPatient(final CFTPatient patient,final Integer idLpu,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTAddNewPatientResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                __envelope.addMapping("http://tempuri.org/","patient",new CFTPatient().getClass());
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "AddNewPatient");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="patient";
                __info.type=CFTPatient.class;
                __info.setValue(patient!=null?patient:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idLpu";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idLpu!=null?idLpu:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTAddNewPatientResult)getResult(CFTAddNewPatientResult.class,__result,"AddNewPatientResult",__envelope);
            }
        },"http://tempuri.org/IHubService/AddNewPatient");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTAddNewPatientResult>> AddNewPatientAsync(final CFTPatient patient,final Integer idLpu,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTAddNewPatientResult>() {
            public CFTAddNewPatientResult Func() throws java.lang.Exception {
                return AddNewPatient( patient,idLpu,guid,idHistory);
            }
        });
    }
    
    public CFTGetDocListFullTreeResult GetDocListFullTree(final Integer idLpu,final String idPat,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTGetDocListFullTreeResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetDocListFullTree");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idLpu";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idLpu!=null?idLpu:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idPat";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idPat!=null?idPat:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTGetDocListFullTreeResult)getResult(CFTGetDocListFullTreeResult.class,__result,"GetDocListFullTreeResult",__envelope);
            }
        },"http://tempuri.org/IHubService/GetDocListFullTree");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTGetDocListFullTreeResult>> GetDocListFullTreeAsync(final Integer idLpu,final String idPat,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTGetDocListFullTreeResult>() {
            public CFTGetDocListFullTreeResult Func() throws java.lang.Exception {
                return GetDocListFullTree( idLpu,idPat,guid,idHistory);
            }
        });
    }
    
    public CFTInspectDoctorsReferalResult InspectDoctorsReferal(final String doctorsReferal,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTInspectDoctorsReferalResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "InspectDoctorsReferal");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="doctorsReferal";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(doctorsReferal!=null?doctorsReferal:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTInspectDoctorsReferalResult)getResult(CFTInspectDoctorsReferalResult.class,__result,"InspectDoctorsReferalResult",__envelope);
            }
        },"http://tempuri.org/IHubService/InspectDoctorsReferal");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTInspectDoctorsReferalResult>> InspectDoctorsReferalAsync(final String doctorsReferal,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTInspectDoctorsReferalResult>() {
            public CFTInspectDoctorsReferalResult Func() throws java.lang.Exception {
                return InspectDoctorsReferal( doctorsReferal,guid,idHistory);
            }
        });
    }
    
    public CFTGetAvaibleAppointmentsResult GetAppointmentsDemandDoctorsReferal(final String idDoc,final Integer idLpu,final String idPat,final CFTEnums.AppointmentType appType,final java.util.Date startVisit,final java.util.Date endVisit,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTGetAvaibleAppointmentsResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetAppointmentsDemandDoctorsReferal");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idDoc!=null?idDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idLpu";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idLpu!=null?idLpu:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idPat";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idPat!=null?idPat:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="appType";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(appType!=null?appType.toString():SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="startVisit";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(startVisit!=null?CFTHelper.getDateTimeFormat().format(startVisit):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="endVisit";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(endVisit!=null?CFTHelper.getDateTimeFormat().format(endVisit):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTGetAvaibleAppointmentsResult)getResult(CFTGetAvaibleAppointmentsResult.class,__result,"GetAppointmentsDemandDoctorsReferalResult",__envelope);
            }
        },"http://tempuri.org/IHubService/GetAppointmentsDemandDoctorsReferal");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTGetAvaibleAppointmentsResult>> GetAppointmentsDemandDoctorsReferalAsync(final String idDoc,final Integer idLpu,final String idPat,final CFTEnums.AppointmentType appType,final java.util.Date startVisit,final java.util.Date endVisit,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTGetAvaibleAppointmentsResult>() {
            public CFTGetAvaibleAppointmentsResult Func() throws java.lang.Exception {
                return GetAppointmentsDemandDoctorsReferal( idDoc,idLpu,idPat,appType,startVisit,endVisit,guid,idHistory);
            }
        });
    }
    
    public CFTGetAvaibleAppointmentsResult GetAvaibleAppointments(final String idDoc,final Integer idLpu,final String idPat,final java.util.Date visitStart,final java.util.Date visitEnd,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTGetAvaibleAppointmentsResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetAvaibleAppointments");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idDoc!=null?idDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idLpu";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idLpu!=null?idLpu:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idPat";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idPat!=null?idPat:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="visitStart";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(visitStart!=null?CFTHelper.getDateTimeFormat().format(visitStart):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="visitEnd";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(visitEnd!=null?CFTHelper.getDateTimeFormat().format(visitEnd):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTGetAvaibleAppointmentsResult)getResult(CFTGetAvaibleAppointmentsResult.class,__result,"GetAvaibleAppointmentsResult",__envelope);
            }
        },"http://tempuri.org/IHubService/GetAvaibleAppointments");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTGetAvaibleAppointmentsResult>> GetAvaibleAppointmentsAsync(final String idDoc,final Integer idLpu,final String idPat,final java.util.Date visitStart,final java.util.Date visitEnd,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTGetAvaibleAppointmentsResult>() {
            public CFTGetAvaibleAppointmentsResult Func() throws java.lang.Exception {
                return GetAvaibleAppointments( idDoc,idLpu,idPat,visitStart,visitEnd,guid,idHistory);
            }
        });
    }
    
    public CFTSetAppointmentResult SetAppointment(final String idAppointment,final Integer idLpu,final String idPat,final String doctorsReferal,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTSetAppointmentResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "SetAppointment");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idAppointment";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idAppointment!=null?idAppointment:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idLpu";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idLpu!=null?idLpu:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idPat";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idPat!=null?idPat:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="doctorsReferal";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(doctorsReferal!=null?doctorsReferal:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTSetAppointmentResult)getResult(CFTSetAppointmentResult.class,__result,"SetAppointmentResult",__envelope);
            }
        },"http://tempuri.org/IHubService/SetAppointment");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTSetAppointmentResult>> SetAppointmentAsync(final String idAppointment,final Integer idLpu,final String idPat,final String doctorsReferal,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTSetAppointmentResult>() {
            public CFTSetAppointmentResult Func() throws java.lang.Exception {
                return SetAppointment( idAppointment,idLpu,idPat,doctorsReferal,guid,idHistory);
            }
        });
    }
    
    public CFTGetAvailableDatesResult GetAvailableDates(final String idDoc,final Integer idLpu,final String idPat,final java.util.Date visitStart,final java.util.Date visitEnd,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTGetAvailableDatesResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetAvailableDates");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idDoc";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idDoc!=null?idDoc:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idLpu";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idLpu!=null?idLpu:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idPat";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idPat!=null?idPat:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="visitStart";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(visitStart!=null?CFTHelper.getDateTimeFormat().format(visitStart):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="visitEnd";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(visitEnd!=null?CFTHelper.getDateTimeFormat().format(visitEnd):SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTGetAvailableDatesResult)getResult(CFTGetAvailableDatesResult.class,__result,"GetAvailableDatesResult",__envelope);
            }
        },"http://tempuri.org/IHubService/GetAvailableDates");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTGetAvailableDatesResult>> GetAvailableDatesAsync(final String idDoc,final Integer idLpu,final String idPat,final java.util.Date visitStart,final java.util.Date visitEnd,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTGetAvailableDatesResult>() {
            public CFTGetAvailableDatesResult Func() throws java.lang.Exception {
                return GetAvailableDates( idDoc,idLpu,idPat,visitStart,visitEnd,guid,idHistory);
            }
        });
    }
    
    public CFTGetDoctorListResult GetDoctorList(final String idSpesiality,final Integer idLpu,final String idPat,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTGetDoctorListResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetDoctorList");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idSpesiality";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idSpesiality!=null?idSpesiality:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idLpu";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idLpu!=null?idLpu:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idPat";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idPat!=null?idPat:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTGetDoctorListResult)getResult(CFTGetDoctorListResult.class,__result,"GetDoctorListResult",__envelope);
            }
        },"http://tempuri.org/IHubService/GetDoctorList");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTGetDoctorListResult>> GetDoctorListAsync(final String idSpesiality,final Integer idLpu,final String idPat,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTGetDoctorListResult>() {
            public CFTGetDoctorListResult Func() throws java.lang.Exception {
                return GetDoctorList( idSpesiality,idLpu,idPat,guid,idHistory);
            }
        });
    }
    
    public CFTGetLPUListResult GetLPUList(final Integer IdDistrict,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTGetLPUListResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetLPUList");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="IdDistrict";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(IdDistrict!=null?IdDistrict:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTGetLPUListResult)getResult(CFTGetLPUListResult.class,__result,"GetLPUListResult",__envelope);
            }
        },"http://tempuri.org/IHubService/GetLPUList");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTGetLPUListResult>> GetLPUListAsync(final Integer IdDistrict,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTGetLPUListResult>() {
            public CFTGetLPUListResult Func() throws java.lang.Exception {
                return GetLPUList( IdDistrict,guid,idHistory);
            }
        });
    }
    
    public CFTGetOrgListResult GetOrgList(final Integer IdDistrict,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTGetOrgListResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetOrgList");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="IdDistrict";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(IdDistrict!=null?IdDistrict:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTGetOrgListResult)getResult(CFTGetOrgListResult.class,__result,"GetOrgListResult",__envelope);
            }
        },"http://tempuri.org/IHubService/GetOrgList");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTGetOrgListResult>> GetOrgListAsync(final Integer IdDistrict,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTGetOrgListResult>() {
            public CFTGetOrgListResult Func() throws java.lang.Exception {
                return GetOrgList( IdDistrict,guid,idHistory);
            }
        });
    }
    
    public CFTGetSpesialityListResult GetSpesialityList(final Integer idLpu,final String idPat,final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTGetSpesialityListResult)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetSpesialityList");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idLpu";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idLpu!=null?idLpu:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idPat";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(idPat!=null?idPat:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTGetSpesialityListResult)getResult(CFTGetSpesialityListResult.class,__result,"GetSpesialityListResult",__envelope);
            }
        },"http://tempuri.org/IHubService/GetSpesialityList");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTGetSpesialityListResult>> GetSpesialityListAsync(final Integer idLpu,final String idPat,final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTGetSpesialityListResult>() {
            public CFTGetSpesialityListResult Func() throws java.lang.Exception {
                return GetSpesialityList( idLpu,idPat,guid,idHistory);
            }
        });
    }
    
    public CFTArrayOfLpuListToRFISZ GetLpuToRFSZIList(final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTArrayOfLpuListToRFISZ)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetLpuToRFSZIList");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTArrayOfLpuListToRFISZ)getResult(CFTArrayOfLpuListToRFISZ.class,__result,"GetLpuToRFSZIListResult",__envelope);
            }
        },"http://tempuri.org/IHubService/GetLpuToRFSZIList");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTArrayOfLpuListToRFISZ>> GetLpuToRFSZIListAsync(final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTArrayOfLpuListToRFISZ>() {
            public CFTArrayOfLpuListToRFISZ Func() throws java.lang.Exception {
                return GetLpuToRFSZIList( guid,idHistory);
            }
        });
    }
    
    public CFTArrayOfDistrict GetDistrictList(final String guid,final Integer idHistory ) throws java.lang.Exception
    {
        return (CFTArrayOfDistrict)execute(new CFTIWcfMethod()
        {
            @Override
            public CFTExtendedSoapSerializationEnvelope CreateSoapEnvelope(){
              CFTExtendedSoapSerializationEnvelope __envelope = createEnvelope();
                SoapObject __soapReq = new SoapObject("http://tempuri.org/", "GetDistrictList");
                __envelope.setOutputSoapObject(__soapReq);
                
                PropertyInfo __info=null;
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="guid";
                __info.type=PropertyInfo.STRING_CLASS;
                __info.setValue(guid!=null?guid:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                __info = new PropertyInfo();
                __info.namespace="http://tempuri.org/";
                __info.name="idHistory";
                __info.type=PropertyInfo.INTEGER_CLASS;
                __info.setValue(idHistory!=null?idHistory:SoapPrimitive.NullSkip);
                __soapReq.addProperty(__info);
                return __envelope;
            }
            
            @Override
            public java.lang.Object ProcessResult(CFTExtendedSoapSerializationEnvelope __envelope,java.lang.Object __result)throws java.lang.Exception {
                return (CFTArrayOfDistrict)getResult(CFTArrayOfDistrict.class,__result,"GetDistrictListResult",__envelope);
            }
        },"http://tempuri.org/IHubService/GetDistrictList");
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< CFTArrayOfDistrict>> GetDistrictListAsync(final String guid,final Integer idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< CFTArrayOfDistrict>() {
            public CFTArrayOfDistrict Func() throws java.lang.Exception {
                return GetDistrictList( guid,idHistory);
            }
        });
    }
    
    public String GetWorkingTime(final String idDoc,final String idLpu,final String visitStart,final String visitEnd,final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> GetWorkingTimeAsync(final String idDoc,final String idLpu,final String visitStart,final String visitEnd,final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return GetWorkingTime( idDoc,idLpu,visitStart,visitEnd,guid,idHistory);
            }
        });
    }
    
    public String GetFullInfoById(final String idDoc,final String idLpu,final String idPat,final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> GetFullInfoByIdAsync(final String idDoc,final String idLpu,final String idPat,final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return GetFullInfoById( idDoc,idLpu,idPat,guid,idHistory);
            }
        });
    }
    
    public String CreateClaimForRefusal(final String idLpu,final String idPat,final String idAppointment,final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> CreateClaimForRefusalAsync(final String idLpu,final String idPat,final String idAppointment,final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CreateClaimForRefusal( idLpu,idPat,idAppointment,guid,idHistory);
            }
        });
    }
    
    public String GetPatientHistory(final String idLpu,final String idPat,final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> GetPatientHistoryAsync(final String idLpu,final String idPat,final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return GetPatientHistory( idLpu,idPat,guid,idHistory);
            }
        });
    }
    
    public String UpdatePhoneByIdPat(final String idLpu,final String idPat,final String homePhone,final String cellPhone,final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> UpdatePhoneByIdPatAsync(final String idLpu,final String idPat,final String homePhone,final String cellPhone,final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return UpdatePhoneByIdPat( idLpu,idPat,homePhone,cellPhone,guid,idHistory);
            }
        });
    }
    
    public String GetHubUserByGuid(final String usersGuid,final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> GetHubUserByGuidAsync(final String usersGuid,final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return GetHubUserByGuid( usersGuid,guid,idHistory);
            }
        });
    }
    
    public String GetErrorList(final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> GetErrorListAsync(final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return GetErrorList( guid,idHistory);
            }
        });
    }
    
    public String SetWaitingList(final String idDoc,final String nameDoc,final String idSpesiality,final String nameSpesiality,final String idLpu,final String rule,final String claim,final String idPat,final String namePat,final String birthday,final String phone,final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> SetWaitingListAsync(final String idDoc,final String nameDoc,final String idSpesiality,final String nameSpesiality,final String idLpu,final String rule,final String claim,final String idPat,final String namePat,final String birthday,final String phone,final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return SetWaitingList( idDoc,nameDoc,idSpesiality,nameSpesiality,idLpu,rule,claim,idPat,namePat,birthday,phone,guid,idHistory);
            }
        });
    }
    
    public String GetStatusAnalysis(final String idAnalysis,final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> GetStatusAnalysisAsync(final String idAnalysis,final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return GetStatusAnalysis( idAnalysis,guid,idHistory);
            }
        });
    }
    
    public String SendNotificationAboutAppointment(final String doctor,final String spesiality,final String idLpu,final String patient,final String appointment,final String appointmentSource,final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> SendNotificationAboutAppointmentAsync(final String doctor,final String spesiality,final String idLpu,final String patient,final String appointment,final String appointmentSource,final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return SendNotificationAboutAppointment( doctor,spesiality,idLpu,patient,appointment,appointmentSource,guid,idHistory);
            }
        });
    }
    
    public String SendNotificationAboutAppointmentStatus(final String doctor,final String spesiality,final String idLpu,final String patient,final String appointment,final String status,final String guid,final String idHistory ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> SendNotificationAboutAppointmentStatusAsync(final String doctor,final String spesiality,final String idLpu,final String patient,final String appointment,final String status,final String guid,final String idHistory)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return SendNotificationAboutAppointmentStatus( doctor,spesiality,idLpu,patient,appointment,status,guid,idHistory);
            }
        });
    }
    
    public String GetTodayAppointments(final String guid ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> GetTodayAppointmentsAsync(final String guid)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return GetTodayAppointments( guid);
            }
        });
    }
    
    public String CheckIn(final String idAppointment ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> CheckInAsync(final String idAppointment)
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return CheckIn( idAppointment);
            }
        });
    }
    
    public String GetVersion( ) throws java.lang.Exception
    {
/*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
        return null;    
    }
    
    public android.os.AsyncTask< Void, Void, CFTOperationResult< String>> GetVersionAsync()
    {
        return executeAsync(new CFTFunctions.IFunc< String>() {
            public String Func() throws java.lang.Exception {
                return GetVersion( );
            }
        });
    }

    
    protected java.lang.Object execute(CFTIWcfMethod wcfMethod,String methodName) throws java.lang.Exception
    {
        org.ksoap2.transport.Transport __httpTransport=createTransport();
        __httpTransport.debug=enableLogging;
        CFTExtendedSoapSerializationEnvelope __envelope=wcfMethod.CreateSoapEnvelope();
        try
        {
            sendRequest(methodName, __envelope, __httpTransport);
            
        }
        finally {
            if (__httpTransport.debug) {
                if (__httpTransport.requestDump != null) {
                    android.util.Log.i("requestDump",__httpTransport.requestDump);    
                    
                }
                if (__httpTransport.responseDump != null) {
                    android.util.Log.i("responseDump",__httpTransport.responseDump);
                }
            }
        }
        java.lang.Object __retObj = __envelope.bodyIn;
        if (__retObj instanceof org.ksoap2.SoapFault){
            org.ksoap2.SoapFault __fault = (org.ksoap2.SoapFault)__retObj;
            throw convertToException(__fault,__envelope);
        }else{
            return wcfMethod.ProcessResult(__envelope,__retObj);
        }
    }
    
    protected < T> android.os.AsyncTask< Void, Void, CFTOperationResult< T>>  executeAsync(final CFTFunctions.IFunc< T> func)
    {
        return new android.os.AsyncTask< Void, Void, CFTOperationResult< T>>()
        {
            @Override
            protected void onPreExecute() {
                callback.Starting();
            };
            @Override
            protected CFTOperationResult< T> doInBackground(Void... params) {
                CFTOperationResult< T> result = new CFTOperationResult< T>();
                try
                {
                    result.Result= func.Func();
                }
                catch(java.lang.Exception ex)
                {
                    ex.printStackTrace();
                    result.Exception=ex;
                }
                return result;
            }
            
            @Override
            protected void onPostExecute(CFTOperationResult< T> result)
            {
                callback.Completed(result);
            }
        }.execute();
    }
        
    java.lang.Exception convertToException(org.ksoap2.SoapFault fault,CFTExtendedSoapSerializationEnvelope envelope)
    {

        return new java.lang.Exception(fault.faultstring);
    }
}


