package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CFTClinic extends AttributeContainer implements KvmSerializable
{

    
    public String Description;
    
    public Integer District;
    
    public Integer IdLPU;
    
    public String LPUFullName;
    
    public String LPUShortName;
    
    public Integer LPUType;

    public CFTClinic ()
    {
    }

    public CFTClinic (java.lang.Object paramObj,CFTExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("Description"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Description = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Description = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("District"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.District = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.District = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("IdLPU"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.IdLPU = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.IdLPU = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("LPUFullName"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.LPUFullName = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.LPUFullName = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("LPUShortName"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.LPUShortName = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.LPUShortName = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("LPUType"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.LPUType = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.LPUType = (Integer)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Description!=null?this.Description:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.District!=null?this.District:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.IdLPU!=null?this.IdLPU:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.LPUFullName!=null?this.LPUFullName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.LPUShortName!=null?this.LPUShortName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.LPUType!=null?this.LPUType:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Description";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "District";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdLPU";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LPUFullName";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LPUShortName";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "LPUType";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

