package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CFTDoctor extends AttributeContainer implements KvmSerializable
{

    
    public String AriaNumber;
    
    public Integer CountFreeParticipantIE;
    
    public Integer CountFreeTicket;
    
    public String IdDoc;
    
    public java.util.Date LastDate;
    
    public String Name;
    
    public java.util.Date NearestDate;
    
    public String Snils;

    public CFTDoctor ()
    {
    }

    public CFTDoctor (java.lang.Object paramObj,CFTExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("AriaNumber"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.AriaNumber = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.AriaNumber = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("CountFreeParticipantIE"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.CountFreeParticipantIE = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.CountFreeParticipantIE = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("CountFreeTicket"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.CountFreeTicket = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.CountFreeTicket = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("IdDoc"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.IdDoc = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.IdDoc = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("LastDate"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.LastDate = CFTHelper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.LastDate = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Name"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Name = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Name = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("NearestDate"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.NearestDate = CFTHelper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.NearestDate = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Snils"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Snils = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Snils = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.AriaNumber!=null?this.AriaNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.CountFreeParticipantIE!=null?this.CountFreeParticipantIE:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.CountFreeTicket!=null?this.CountFreeTicket:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.IdDoc!=null?this.IdDoc:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.LastDate!=null?CFTHelper.getDateTimeFormat().format(this.LastDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.Name!=null?this.Name:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.NearestDate!=null?CFTHelper.getDateTimeFormat().format(this.NearestDate):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Snils!=null?this.Snils:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AriaNumber";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "CountFreeParticipantIE";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "CountFreeTicket";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IdDoc";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LastDate";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Name";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NearestDate";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Snils";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

