package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CFTDistrict extends AttributeContainer implements KvmSerializable
{

    
    public String DistrictName;
    
    public Integer IdDistrict;
    
    public Double Okato;

    public CFTDistrict ()
    {
    }

    public CFTDistrict (java.lang.Object paramObj,CFTExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("DistrictName"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.DistrictName = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.DistrictName = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("IdDistrict"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.IdDistrict = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.IdDistrict = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Okato"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Okato = new Double(j.toString());
                            }
                        }
                        else if (obj instanceof Double){
                            this.Okato = (Double)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.DistrictName!=null?this.DistrictName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.IdDistrict!=null?this.IdDistrict:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Okato!=null?this.Okato:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DistrictName";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdDistrict";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==2)
        {
            info.type = Double.class;
            info.name = "Okato";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

