package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CFTEssence extends AttributeContainer implements KvmSerializable
{

    
    public String Description;
    
    public String IdEssence;
    
    public CFTArrayOfEssence ListEssence;
    
    public String NameEssence;

    public CFTEssence ()
    {
    }

    public CFTEssence (java.lang.Object paramObj,CFTExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("Description"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Description = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Description = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("IdEssence"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.IdEssence = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.IdEssence = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("ListEssence"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.ListEssence = new CFTArrayOfEssence(j,__envelope);
                    }
                    continue;
                }
                if (info.name.equals("NameEssence"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.NameEssence = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.NameEssence = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Description!=null?this.Description:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.IdEssence!=null?this.IdEssence:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.ListEssence!=null?this.ListEssence:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.NameEssence!=null?this.NameEssence:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Description";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IdEssence";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ListEssence";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NameEssence";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

