package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------



import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.*;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;

import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Vector;
import java.io.StringReader;
import java.io.StringWriter;

public class CFTExtendedSoapSerializationEnvelope extends SoapSerializationEnvelope {
    static HashMap< java.lang.String,java.lang.Class> classNames = new HashMap< java.lang.String, java.lang.Class>();
    static {
        classNames.put("http://schemas.datacontract.org/2004/07/System.Collections.Generic^^KeyValuePairOfintstring",CFTKeyValuePairOfintstring.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^Patient",CFTPatient.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^CheckPatientResult",CFTCheckPatientResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^MethodResult",CFTMethodResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^Error",CFTError.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^CreateClaimForRefusalResult",CFTCreateClaimForRefusalResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetErrorListResult",CFTGetErrorListResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetVersionResult",CFTGetVersionResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^SearchTop10PatientResult",CFTSearchTop10PatientResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^AddNewPatientResult",CFTAddNewPatientResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetDocListFullTreeResult",CFTGetDocListFullTreeResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^Essence",CFTEssence.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^InspectDoctorsReferalResult",CFTInspectDoctorsReferalResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetAvaibleAppointmentsResult",CFTGetAvaibleAppointmentsResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^Appointment",CFTAppointment.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^StatusAppointment",CFTStatusAppointment.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^NoticeAppointment",CFTNoticeAppointment.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^SetAppointmentResult",CFTSetAppointmentResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetAvailableDatesResult",CFTGetAvailableDatesResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetDoctorListResult",CFTGetDoctorListResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^Doctor",CFTDoctor.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetLPUListResult",CFTGetLPUListResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^Clinic",CFTClinic.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetOrgListResult",CFTGetOrgListResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^Org",CFTOrg.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetSpesialityListResult",CFTGetSpesialityListResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^Spesiality",CFTSpesiality.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetWorkingTimeResult",CFTGetWorkingTimeResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^WorkingTime",CFTWorkingTime.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetFullInfoByIdResult",CFTGetFullInfoByIdResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetPatientHistoryResult",CFTGetPatientHistoryResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^HistoryRefusal",CFTHistoryRefusal.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^HistoryVisit",CFTHistoryVisit.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^User",CFTUser.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^HubUser",CFTHubUser.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^UpdatePhoneByIdPatResult",CFTUpdatePhoneByIdPatResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetHubUserByGuidResult",CFTGetHubUserByGuidResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^SetWaitingListResult",CFTSetWaitingListResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetStatusAnalysisResult",CFTGetStatusAnalysisResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^SendNotificationAboutAppointmentResult",CFTSendNotificationAboutAppointmentResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^SendNotificationAboutAppointmentStatusResult",CFTSendNotificationAboutAppointmentStatusResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^GetTodayAppointmentResult",CFTGetTodayAppointmentResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^SchedulerOfDoctor",CFTSchedulerOfDoctor.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^SchedulerOfDoctorItem",CFTSchedulerOfDoctorItem.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^CheckInResult",CFTCheckInResult.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^LpuListToRFISZ",CFTLpuListToRFISZ.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^District",CFTDistrict.class);
        classNames.put("http://schemas.microsoft.com/2003/10/Serialization/Arrays^^ArrayOfdateTime",CFTArrayOfdateTime.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfError",CFTArrayOfError.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfPatient",CFTArrayOfPatient.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfEssence",CFTArrayOfEssence.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfAppointment",CFTArrayOfAppointment.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfDoctor",CFTArrayOfDoctor.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfClinic",CFTArrayOfClinic.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfOrg",CFTArrayOfOrg.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfSpesiality",CFTArrayOfSpesiality.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfWorkingTime",CFTArrayOfWorkingTime.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfHistoryRefusal",CFTArrayOfHistoryRefusal.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfHistoryVisit",CFTArrayOfHistoryVisit.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfHubUser",CFTArrayOfHubUser.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfSchedulerOfDoctor",CFTArrayOfSchedulerOfDoctor.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfSchedulerOfDoctorItem",CFTArrayOfSchedulerOfDoctorItem.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfLpuListToRFISZ",CFTArrayOfLpuListToRFISZ.class);
        classNames.put("http://schemas.datacontract.org/2004/07/HubService2^^ArrayOfDistrict",CFTArrayOfDistrict.class);
    }   

    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";

    public CFTExtendedSoapSerializationEnvelope() {
        this(SoapEnvelope.VER11);
    }

    public CFTExtendedSoapSerializationEnvelope(int soapVersion) {
        super(soapVersion);
        implicitTypes = true;
        setAddAdornments(false);
        new CFTMarshalGuid().register(this);
        new MarshalFloat().register(this);
    }

    

    @Override
    protected void writeProperty(XmlSerializer writer, java.lang.Object obj, PropertyInfo type) throws IOException {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (obj == null || obj== SoapPrimitive.NullNilElement) {
            writer.attribute(xsi, version >= VER12 ? NIL_LABEL : NULL_LABEL, "true");
            return;
        }
        java.lang.Object[] qName = getInfo(null, obj);
        if (!type.multiRef && qName[2] == null )
        {

            if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!=java.lang.String.class  )) {
                java.lang.String xmlName=CFTHelper.getKeyByValue(classNames,obj.getClass());
                if(xmlName!=null) {
                    java.lang.String[] parts = xmlName.split("\\^\\^");
                    java.lang.String prefix = writer.getPrefix(parts[0], true);
                    writer.attribute(xsi, TYPE_LABEL, prefix + ":" + parts[1]);
                }
                else
                {
                    if(type.type instanceof String) {
                        java.lang.String xsdPrefix = writer.getPrefix(xsd, true);
                        java.lang.String myType = (java.lang.String) type.type;
                        java.lang.String[] parts = myType.split("\\^\\^");
                        if (parts.length == 2) {
                            xsdPrefix = writer.getPrefix(parts[0], true);
                            myType = parts[1];
                        }

                        writer.attribute(xsi, TYPE_LABEL, xsdPrefix + ":" + myType);
                    }
                    else
                    {
                        java.lang.String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }

                }
            }
            //super.writeProperty(writer,obj,type);

            //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
            //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
            writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
        }
        else {
            super.writeProperty(writer, obj, type);
        }
    }
    public SoapObject GetExceptionDetail(Element detailElement,java.lang.String exceptionElementNS,java.lang.String exceptionElementName)
    {
        int index=detailElement.indexOf(exceptionElementNS,exceptionElementName,0);
        if(index>-1)
        {
            Element errorElement=detailElement.getElement(index);
            return GetSoapObject(errorElement);
        }
        return null;
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();

            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);

            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
    }

    public java.lang.Object GetHeader(Element detailElement) {
        if(detailElement.getChildCount()>0 && detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }
    
    public java.lang.Object get(java.lang.Object soap,java.lang.Class cl,boolean typeFromClass)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            if(soap instanceof Vector || typeFromClass)
            {
                Constructor ctor = cl.getConstructor(java.lang.Object.class,CFTExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
            {
                if(soap instanceof SoapObject)
                {
                    if(cl ==SoapObject.class)
                    {
                        return soap;
                    }
                    java.lang.String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                Constructor ctor = cl.getConstructor(java.lang.Object.class,CFTExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
            return null;
        }
    }

} 

