package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CFTHistoryVisit extends AttributeContainer implements KvmSerializable
{

    
    public java.util.Date DateCreatedAppointment;
    
    public CFTDoctor DoctorBringReferal;
    
    public CFTDoctor DoctorRendingConsultation;
    
    public String IdAppointment;
    
    public CFTSpesiality SpecialityBringReferal;
    
    public CFTSpesiality SpecialityRendingConsultation;
    
    public CFTUser UserCreatedAppointment;
    
    public java.util.Date VisitStart;

    public CFTHistoryVisit ()
    {
    }

    public CFTHistoryVisit (java.lang.Object paramObj,CFTExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("DateCreatedAppointment"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.DateCreatedAppointment = CFTHelper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.DateCreatedAppointment = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("DoctorBringReferal"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.DoctorBringReferal = (CFTDoctor)__envelope.get(j,CFTDoctor.class,false);
                    }
                    continue;
                }
                if (info.name.equals("DoctorRendingConsultation"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.DoctorRendingConsultation = (CFTDoctor)__envelope.get(j,CFTDoctor.class,false);
                    }
                    continue;
                }
                if (info.name.equals("IdAppointment"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.IdAppointment = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.IdAppointment = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("SpecialityBringReferal"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.SpecialityBringReferal = (CFTSpesiality)__envelope.get(j,CFTSpesiality.class,false);
                    }
                    continue;
                }
                if (info.name.equals("SpecialityRendingConsultation"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.SpecialityRendingConsultation = (CFTSpesiality)__envelope.get(j,CFTSpesiality.class,false);
                    }
                    continue;
                }
                if (info.name.equals("UserCreatedAppointment"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.UserCreatedAppointment = (CFTUser)__envelope.get(j,CFTUser.class,false);
                    }
                    continue;
                }
                if (info.name.equals("VisitStart"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.VisitStart = CFTHelper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.VisitStart = (java.util.Date)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.DateCreatedAppointment!=null?CFTHelper.getDateTimeFormat().format(this.DateCreatedAppointment):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.DoctorBringReferal!=null?this.DoctorBringReferal:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.DoctorRendingConsultation!=null?this.DoctorRendingConsultation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.IdAppointment!=null?this.IdAppointment:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.SpecialityBringReferal!=null?this.SpecialityBringReferal:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.SpecialityRendingConsultation!=null?this.SpecialityRendingConsultation:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.UserCreatedAppointment!=null?this.UserCreatedAppointment:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.VisitStart!=null?CFTHelper.getDateTimeFormat().format(this.VisitStart):SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 8;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateCreatedAppointment";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==1)
        {
            info.type = CFTDoctor.class;
            info.name = "DoctorBringReferal";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==2)
        {
            info.type = CFTDoctor.class;
            info.name = "DoctorRendingConsultation";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IdAppointment";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==4)
        {
            info.type = CFTSpesiality.class;
            info.name = "SpecialityBringReferal";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==5)
        {
            info.type = CFTSpesiality.class;
            info.name = "SpecialityRendingConsultation";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==6)
        {
            info.type = CFTUser.class;
            info.name = "UserCreatedAppointment";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "VisitStart";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

