package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------



public interface CFTIServiceEvents
{
    public void Starting();
    public void Completed(CFTOperationResult result);
}
