package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CFTLpuListToRFISZ extends AttributeContainer implements KvmSerializable
{

    
    public String Address;
    
    public Double ExternalGisId;
    
    public Double ExternalHubId;
    
    public Integer Id;
    
    public Integer IdDistrict;
    
    public Boolean InfoStand;
    
    public String InternetReference;
    
    public Boolean IsEnableAppointment;
    
    public Boolean IsEnableInternet;
    
    public String LpuName;
    
    public String LpuType;
    
    public String PhoneCallCentre;
    
    public String WorkTime;
    
    public String email;

    public CFTLpuListToRFISZ ()
    {
    }

    public CFTLpuListToRFISZ (java.lang.Object paramObj,CFTExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("Address"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Address = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Address = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("ExternalGisId"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.ExternalGisId = new Double(j.toString());
                            }
                        }
                        else if (obj instanceof Double){
                            this.ExternalGisId = (Double)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("ExternalHubId"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.ExternalHubId = new Double(j.toString());
                            }
                        }
                        else if (obj instanceof Double){
                            this.ExternalHubId = (Double)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Id"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Id = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.Id = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("IdDistrict"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.IdDistrict = Integer.parseInt(j.toString());
                            }
                        }
                        else if (obj instanceof Integer){
                            this.IdDistrict = (Integer)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("InfoStand"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.InfoStand = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.InfoStand = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("InternetReference"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.InternetReference = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.InternetReference = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("IsEnableAppointment"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.IsEnableAppointment = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.IsEnableAppointment = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("IsEnableInternet"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.IsEnableInternet = new Boolean(j.toString());
                            }
                        }
                        else if (obj instanceof Boolean){
                            this.IsEnableInternet = (Boolean)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("LpuName"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.LpuName = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.LpuName = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("LpuType"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.LpuType = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.LpuType = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("PhoneCallCentre"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.PhoneCallCentre = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.PhoneCallCentre = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("WorkTime"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.WorkTime = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.WorkTime = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("email"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.email = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.email = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Address!=null?this.Address:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.ExternalGisId!=null?this.ExternalGisId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.ExternalHubId!=null?this.ExternalHubId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Id!=null?this.Id:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.IdDistrict!=null?this.IdDistrict:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.InfoStand!=null?this.InfoStand:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.InternetReference!=null?this.InternetReference:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.IsEnableAppointment!=null?this.IsEnableAppointment:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.IsEnableInternet!=null?this.IsEnableInternet:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.LpuName!=null?this.LpuName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.LpuType!=null?this.LpuType:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.PhoneCallCentre!=null?this.PhoneCallCentre:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==12)
        {
            return this.WorkTime!=null?this.WorkTime:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==13)
        {
            return this.email!=null?this.email:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 14;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Address";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==1)
        {
            info.type = Double.class;
            info.name = "ExternalGisId";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==2)
        {
            info.type = Double.class;
            info.name = "ExternalHubId";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "Id";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "IdDistrict";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "InfoStand";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InternetReference";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "IsEnableAppointment";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "IsEnableInternet";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LpuName";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "LpuType";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PhoneCallCentre";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==12)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "WorkTime";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==13)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "email";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

