package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CFTPatient extends AttributeContainer implements KvmSerializable
{

    
    public String AriaNumber;
    
    public java.util.Date Birthday;
    
    public String CellPhone;
    
    public String Document_N;
    
    public String Document_S;
    
    public String HomePhone;
    
    public String IdPat;
    
    public String Name;
    
    public String Polis_N;
    
    public String Polis_S;
    
    public String SecondName;
    
    public String Surname;

    public CFTPatient ()
    {
    }

    public CFTPatient (java.lang.Object paramObj,CFTExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("AriaNumber"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.AriaNumber = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.AriaNumber = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Birthday"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Birthday = CFTHelper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.Birthday = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("CellPhone"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.CellPhone = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.CellPhone = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Document_N"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Document_N = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Document_N = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Document_S"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Document_S = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Document_S = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("HomePhone"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.HomePhone = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.HomePhone = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("IdPat"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.IdPat = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.IdPat = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Name"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Name = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Name = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Polis_N"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Polis_N = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Polis_N = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Polis_S"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Polis_S = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Polis_S = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("SecondName"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.SecondName = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.SecondName = (String)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Surname"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.Surname = j.toString();
                            }
                        }
                        else if (obj instanceof String){
                            this.Surname = (String)obj;
                        }
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.AriaNumber!=null?this.AriaNumber:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.Birthday!=null?CFTHelper.getDateTimeFormat().format(this.Birthday):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.CellPhone!=null?this.CellPhone:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return this.Document_N!=null?this.Document_N:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==4)
        {
            return this.Document_S!=null?this.Document_S:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==5)
        {
            return this.HomePhone!=null?this.HomePhone:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==6)
        {
            return this.IdPat!=null?this.IdPat:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==7)
        {
            return this.Name!=null?this.Name:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==8)
        {
            return this.Polis_N!=null?this.Polis_N:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==9)
        {
            return this.Polis_S!=null?this.Polis_S:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==10)
        {
            return this.SecondName!=null?this.SecondName:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==11)
        {
            return this.Surname!=null?this.Surname:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 12;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "AriaNumber";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Birthday";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CellPhone";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Document_N";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Document_S";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HomePhone";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==6)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "IdPat";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==7)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Name";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==8)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Polis_N";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==9)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Polis_S";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==10)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SecondName";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==11)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Surname";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

