package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CFTSchedulerOfDoctorItem extends AttributeContainer implements KvmSerializable
{

    
    public CFTAppointment AppointmentItem;
    
    public java.util.Date DateStartCheckIn;
    
    public CFTPatient Pat;

    public CFTSchedulerOfDoctorItem ()
    {
    }

    public CFTSchedulerOfDoctorItem (java.lang.Object paramObj,CFTExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("AppointmentItem"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.AppointmentItem = (CFTAppointment)__envelope.get(j,CFTAppointment.class,false);
                    }
                    continue;
                }
                if (info.name.equals("DateStartCheckIn"))
                {
                    if(obj!=null)
                    {
        
                        if (obj.getClass().equals(SoapPrimitive.class))
                        {
                            SoapPrimitive j =(SoapPrimitive) obj;
                            if(j.toString()!=null)
                            {
                                this.DateStartCheckIn = CFTHelper.ConvertFromWebService(j.toString());
                            }
                        }
                        else if (obj instanceof java.util.Date){
                            this.DateStartCheckIn = (java.util.Date)obj;
                        }
                    }
                    continue;
                }
                if (info.name.equals("Pat"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.Pat = (CFTPatient)__envelope.get(j,CFTPatient.class,false);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.AppointmentItem!=null?this.AppointmentItem:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.DateStartCheckIn!=null?CFTHelper.getDateTimeFormat().format(this.DateStartCheckIn):SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return this.Pat!=null?this.Pat:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = CFTAppointment.class;
            info.name = "AppointmentItem";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DateStartCheckIn";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==2)
        {
            info.type = CFTPatient.class;
            info.name = "Pat";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

