package ru.hardhill.hubservice;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.0.1.8
//
// Created by Quasar Development at 13/02/2017
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class CFTSchedulerOfDoctor extends AttributeContainer implements KvmSerializable
{

    
    public CFTDoctor Doc;
    
    public CFTArrayOfSchedulerOfDoctorItem ShedulerOfDoctorItemCollection;

    public CFTSchedulerOfDoctor ()
    {
    }

    public CFTSchedulerOfDoctor (java.lang.Object paramObj,CFTExtendedSoapSerializationEnvelope __envelope)
    {
	    
	    if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;


        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                //if you have compilation error here, please use a ksoap2.jar and ExKsoap2.jar from libs folder (in the generated zip file)
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                java.lang.Object obj = info.getValue(); 
                if (info.name.equals("Doc"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.Doc = (CFTDoctor)__envelope.get(j,CFTDoctor.class,false);
                    }
                    continue;
                }
                if (info.name.equals("ShedulerOfDoctorItemCollection"))
                {
                    if(obj!=null)
                    {
                        java.lang.Object j = obj;
                        this.ShedulerOfDoctorItemCollection = new CFTArrayOfSchedulerOfDoctorItem(j,__envelope);
                    }
                    continue;
                }

            }

        }



    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.Doc!=null?this.Doc:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.ShedulerOfDoctorItemCollection!=null?this.ShedulerOfDoctorItemCollection:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = CFTDoctor.class;
            info.name = "Doc";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ShedulerOfDoctorItemCollection";
            info.namespace= "http://schemas.datacontract.org/2004/07/HubService2";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

    
}

